
# BIN: test executable filename.
BIN=ripley

# SRC: source filenames.
SRC=ripley.c

# DAT: output data filenames.
DAT=mean.dat var.dat model.dat

# TESTFLAGS: environment variables to set during testing.
TESTFLAGS=RNG_SEED=7321

# include the testing base makefile.
include ../tests.mk

