
# BIN: test executable filename.
BIN=multexp

# SRC: source filenames.
SRC=multexp.c

# DAT: output data filenames.
DAT=mean.dat var.dat model.p0.dat

# include the testing base makefile.
include ../tests.mk

