
# test executable filename.
BIN=co2

# source filenames.
SRC=co2.c

# output data filenames.
DAT=  mean-a.dat var-a.dat model-a.p0.dat
DAT+= mean-b.dat var-b.dat model-b.p0.dat
DAT+= $(BIN)-a.log $(BIN)-b.log

# include the base testing makefile.
include ../tests.mk

