
# test executable filename.
BIN=ping

# source filenames.
SRC=ping.c

# output data filenames.
DAT=mean.dat var.dat model.p0.dat

# environment variables to set during testing.
TESTFLAGS=RNG_SEED=7321

# include the base testing makefile.
include ../tests.mk

