
# BIN: test executable filename.
BIN=cosines

# SRC: source filenames.
SRC=cosines.c

# DAT: output data filenames.
DAT=mean.dat var.dat model.p0.dat

# TESTFLAGS: environment variables to set during testing.
TESTFLAGS=RNG_SEED=7321

# include the testing base makefile.
include ../tests.mk

