
# BIN: test executable filename.
BIN=poly

# SRC: source filenames.
SRC=poly.c

# DAT: output data filenames.
DAT=mean.dat var.dat model.p0.dat

# include the testing base makefile.
include ../tests.mk

