
# BIN: test executable filename.
BIN=ch4

# SRC: source filenames.
SRC=ch4.c

# DAT: output data filenames.
DAT=mean.dat var.dat model.p0.dat

# include the testing base makefile.
include ../tests.mk

