
# BIN: test executable filename.
BIN=ch4

# SRC: source filenames.
SRC=ch4.c

# DAT: output data filenames.
DAT=  mean-a.dat var-a.dat model-a.p0.dat
DAT+= mean-b.dat var-b.dat model-b.p0.dat
DAT+= $(BIN)-a.log $(BIN)-b.log

# include the testing base makefile.
include ../tests.mk

